
import java.awt.Color;
import static java.lang.System.exit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;
import static javax.swing.UIManager.getString;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        PreparedStatement st;
        ResultSet rs;
        String query="SELECT * FROM menu";
        try{
            st=db_connection.getConnection().prepareStatement(query);
            rs=st.executeQuery();
            String mname;
            String mprice;
            if(rs.next()){
                mname=rs.getString("name");
                mprice=rs.getString("price");
                jTextField2_MNm.setText(mname);
                jTextField2_MPr.setText(mprice + " Rs ");
            }
            if(rs.next()){
                mname=rs.getString("name");
                mprice=rs.getString("price");
                jTextField2_CNm.setText(mname);
                jTextField3_CPr.setText(mprice + " Rs ");
            }
            if(rs.next()){
                mname=rs.getString("name");
                mprice=rs.getString("price");
                jTextField2_QNm.setText(mname);
                jTextField4_QPr.setText(mprice + " Rs ");
            }
            if(rs.next()){
                mname=rs.getString("name");
                mprice=rs.getString("price");
                jTextField2_PNm.setText(mname);
                jTextField5_PPr.setText(mprice + " Rs ");
            }
            if(rs.next()){
                mname=rs.getString("name");
                mprice=rs.getString("price");
                jTextField2_SNm.setText(mname);
                jTextField6_SPr.setText(mprice + " Rs ");
            }
            if(rs.next()){
                mname=rs.getString("name");
                mprice=rs.getString("price");
                jTextField2_FNm.setText(mname);
                jTextField7_FPr.setText(mprice + " Rs ");
            }  
        }
        catch(Exception ex){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jColorChooser1 = new javax.swing.JColorChooser();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1_M = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3_C = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton6_S = new javax.swing.JButton();
        jTextField6_SPr = new javax.swing.JTextField();
        jTextField2_SNm = new javax.swing.JTextField();
        jTextField3_CPr = new javax.swing.JTextField();
        jTextField2_CNm = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4_Q = new javax.swing.JButton();
        jTextField4_QPr = new javax.swing.JTextField();
        jTextField2_QNm = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton5_P = new javax.swing.JButton();
        jTextField5_PPr = new javax.swing.JTextField();
        jTextField2_PNm = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton7_F = new javax.swing.JButton();
        jTextField7_FPr = new javax.swing.JTextField();
        jTextField2_FNm = new javax.swing.JTextField();
        jTextField2_MPr = new javax.swing.JTextField();
        jTextField2_MNm = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5_home = new javax.swing.JMenu();
        jMenu12_cart = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        label1.setText("label1");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel2.setMaximumSize(new java.awt.Dimension(361, 162));
        jLabel2.setMinimumSize(new java.awt.Dimension(361, 162));

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel8.setText("Marinara Pizza");

        jLabel9.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel9.setText("PRICE: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("1000.00 PKR");

        jButton2.setBackground(new java.awt.Color(204, 0, 204));
        jButton2.setText("Add to Cart");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu10.setText("jMenu10");

        jMenu11.setText("jMenu11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setMaximumSize(new java.awt.Dimension(361, 162));
        jLabel1.setMinimumSize(new java.awt.Dimension(361, 162));

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel6.setText("PRICE: ");

        jButton1_M.setBackground(new java.awt.Color(248, 148, 6));
        jButton1_M.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton1_M.setText("Add to Cart");
        jButton1_M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_MMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1_MMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1_MMouseExited(evt);
            }
        });
        jButton1_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_MActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (2).jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel3.setMaximumSize(new java.awt.Dimension(361, 162));
        jLabel3.setMinimumSize(new java.awt.Dimension(361, 162));

        jLabel12.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel12.setText("PRICE: ");

        jButton3_C.setBackground(new java.awt.Color(248, 148, 6));
        jButton3_C.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton3_C.setText("Add to Cart");
        jButton3_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_CMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3_CMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3_CMouseExited(evt);
            }
        });
        jButton3_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_CActionPerformed(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).jpg"))); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel21.setMaximumSize(new java.awt.Dimension(361, 162));
        jLabel21.setMinimumSize(new java.awt.Dimension(361, 162));

        jLabel23.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel23.setText("PRICE: ");

        jButton6_S.setBackground(new java.awt.Color(248, 148, 6));
        jButton6_S.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton6_S.setText("Add to Cart");
        jButton6_S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6_SMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6_SMouseExited(evt);
            }
        });
        jButton6_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_SActionPerformed(evt);
            }
        });

        jTextField6_SPr.setEditable(false);
        jTextField6_SPr.setBackground(new java.awt.Color(108, 122, 137));
        jTextField6_SPr.setForeground(new java.awt.Color(236, 240, 241));

        jTextField2_SNm.setEditable(false);
        jTextField2_SNm.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2_SNm.setForeground(new java.awt.Color(236, 240, 241));
        jTextField2_SNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_SNmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6_SPr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2_SNm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6_S, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextField2_SNm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6_SPr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addComponent(jButton6_S, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField3_CPr.setEditable(false);
        jTextField3_CPr.setBackground(new java.awt.Color(108, 122, 137));
        jTextField3_CPr.setForeground(new java.awt.Color(236, 240, 241));

        jTextField2_CNm.setEditable(false);
        jTextField2_CNm.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2_CNm.setForeground(new java.awt.Color(236, 240, 241));
        jTextField2_CNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_CNmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3_CPr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2_CNm, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3_C, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3_C, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField2_CNm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3_CPr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (3).jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel4.setMaximumSize(new java.awt.Dimension(361, 162));
        jLabel4.setMinimumSize(new java.awt.Dimension(361, 162));

        jLabel15.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel15.setText("PRICE: ");

        jButton4_Q.setBackground(new java.awt.Color(248, 148, 6));
        jButton4_Q.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton4_Q.setText("Add to Cart");
        jButton4_Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4_QMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4_QMouseExited(evt);
            }
        });
        jButton4_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_QActionPerformed(evt);
            }
        });

        jTextField4_QPr.setEditable(false);
        jTextField4_QPr.setBackground(new java.awt.Color(108, 122, 137));
        jTextField4_QPr.setForeground(new java.awt.Color(236, 240, 241));

        jTextField2_QNm.setEditable(false);
        jTextField2_QNm.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2_QNm.setForeground(new java.awt.Color(236, 240, 241));
        jTextField2_QNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_QNmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4_QPr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2_QNm, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField2_QNm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4_QPr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel17.setMaximumSize(new java.awt.Dimension(361, 162));
        jLabel17.setMinimumSize(new java.awt.Dimension(361, 162));

        jLabel19.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel19.setText("PRICE: ");

        jButton5_P.setBackground(new java.awt.Color(248, 148, 6));
        jButton5_P.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton5_P.setText("Add to Cart");
        jButton5_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5_PMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5_PMouseExited(evt);
            }
        });
        jButton5_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_PActionPerformed(evt);
            }
        });

        jTextField5_PPr.setEditable(false);
        jTextField5_PPr.setBackground(new java.awt.Color(108, 122, 137));
        jTextField5_PPr.setForeground(new java.awt.Color(236, 240, 241));

        jTextField2_PNm.setEditable(false);
        jTextField2_PNm.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2_PNm.setForeground(new java.awt.Color(236, 240, 241));
        jTextField2_PNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_PNmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5_PPr))
                            .addComponent(jTextField2_PNm, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5_P, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5_P, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextField2_PNm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jTextField5_PPr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel25.setMaximumSize(new java.awt.Dimension(361, 162));
        jLabel25.setMinimumSize(new java.awt.Dimension(361, 162));

        jLabel27.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel27.setText("PRICE: ");

        jButton7_F.setBackground(new java.awt.Color(248, 148, 6));
        jButton7_F.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton7_F.setText("Add to Cart");
        jButton7_F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7_FMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7_FMouseExited(evt);
            }
        });
        jButton7_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_FActionPerformed(evt);
            }
        });

        jTextField7_FPr.setEditable(false);
        jTextField7_FPr.setBackground(new java.awt.Color(108, 122, 137));
        jTextField7_FPr.setForeground(new java.awt.Color(236, 240, 241));

        jTextField2_FNm.setEditable(false);
        jTextField2_FNm.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2_FNm.setForeground(new java.awt.Color(236, 240, 241));
        jTextField2_FNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_FNmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7_FPr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField2_FNm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7_F, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTextField2_FNm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7_FPr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)))
                    .addComponent(jButton7_F, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField2_MPr.setEditable(false);
        jTextField2_MPr.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2_MPr.setForeground(new java.awt.Color(236, 240, 241));
        jTextField2_MPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_MPrActionPerformed(evt);
            }
        });

        jTextField2_MNm.setEditable(false);
        jTextField2_MNm.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2_MNm.setForeground(new java.awt.Color(236, 240, 241));
        jTextField2_MNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_MNmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2_MPr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2_MNm))
                        .addGap(23, 23, 23)
                        .addComponent(jButton1_M, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField2_MNm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2_MPr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jButton1_M, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(772, 772, 772))
        );

        jButton8.setBackground(new java.awt.Color(248, 148, 6));
        jButton8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton8.setText("Confirm");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jMenu5_home.setText("Home");
        jMenu5_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5_homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5_home);

        jMenu12_cart.setText("Cart");
        jMenu12_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12_cartMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu12_cart);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_MActionPerformed
        addToCart(1);
    }//GEN-LAST:event_jButton1_MActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        OrderCart c=new OrderCart();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
        c.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_PActionPerformed
        // TODO add your handling code here:
        addToCart(4);
    }//GEN-LAST:event_jButton5_PActionPerformed

    private void jButton6_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_SActionPerformed
        // TODO add your handling code here:
        addToCart(5);
    }//GEN-LAST:event_jButton6_SActionPerformed

    private void jButton3_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_CActionPerformed
        // TODO add your handling code here:
        addToCart(2);
    }//GEN-LAST:event_jButton3_CActionPerformed

    private void jButton4_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_QActionPerformed
        // TODO add your handling code here:
        addToCart(3);
    }//GEN-LAST:event_jButton4_QActionPerformed

    private void jButton7_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_FActionPerformed
        // TODO add your handling code here:
        addToCart(6);
    }//GEN-LAST:event_jButton7_FActionPerformed

    private void jMenu5_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5_homeMouseClicked
        // TODO add your handling code here:
        homeScreen h=new homeScreen();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
        h.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu5_homeMouseClicked

    private void jMenu12_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12_cartMouseClicked
        // TODO add your handling code here:
        OrderCart c=new OrderCart();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
        c.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu12_cartMouseClicked

    private void jTextField2_MPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_MPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_MPrActionPerformed

    private void jButton1_MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_MMouseClicked
 
    }//GEN-LAST:event_jButton1_MMouseClicked

    private void jTextField2_MNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_MNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_MNmActionPerformed

    private void jTextField2_QNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_QNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_QNmActionPerformed

    private void jTextField2_CNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_CNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_CNmActionPerformed

    private void jTextField2_PNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_PNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_PNmActionPerformed

    private void jTextField2_SNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_SNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_SNmActionPerformed

    private void jTextField2_FNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_FNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_FNmActionPerformed

    private void jButton1_MMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_MMouseEntered
        // TODO add your handling code here:
        jButton1_M.setForeground(Color.white);
        jButton1_M.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_jButton1_MMouseEntered

    private void jButton1_MMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_MMouseExited
        // TODO add your handling code here:
        jButton1_M.setForeground(Color.black);
        jButton1_M.setBackground(new Color(248,148,6));
    }//GEN-LAST:event_jButton1_MMouseExited

    private void jButton3_CMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_CMouseEntered
        // TODO add your handling code here:
        jButton3_C.setForeground(Color.white);
        jButton3_C.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_jButton3_CMouseEntered

    private void jButton3_CMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_CMouseExited
        // TODO add your handling code here:
        jButton3_C.setForeground(Color.black);
        jButton3_C.setBackground(new Color(248,148,6));
    }//GEN-LAST:event_jButton3_CMouseExited

    private void jButton3_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_CMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_CMouseClicked

    private void jButton4_QMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_QMouseEntered
        // TODO add your handling code here:
        jButton4_Q.setForeground(Color.white);
        jButton4_Q.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_jButton4_QMouseEntered

    private void jButton4_QMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_QMouseExited
        // TODO add your handling code here:
        jButton4_Q.setForeground(Color.black);
        jButton4_Q.setBackground(new Color(248,148,6));
    }//GEN-LAST:event_jButton4_QMouseExited

    private void jButton5_PMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_PMouseEntered
        // TODO add your handling code here:
        jButton5_P.setForeground(Color.white);
        jButton5_P.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_jButton5_PMouseEntered

    private void jButton5_PMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_PMouseExited
        // TODO add your handling code here:
        jButton5_P.setForeground(Color.black);
        jButton5_P.setBackground(new Color(248,148,6));
    }//GEN-LAST:event_jButton5_PMouseExited

    private void jButton6_SMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6_SMouseEntered
        // TODO add your handling code here:
        jButton6_S.setForeground(Color.white);
        jButton6_S.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_jButton6_SMouseEntered

    private void jButton6_SMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6_SMouseExited
        // TODO add your handling code here:
        jButton6_S.setForeground(Color.black);
        jButton6_S.setBackground(new Color(248,148,6));
    }//GEN-LAST:event_jButton6_SMouseExited

    private void jButton7_FMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7_FMouseEntered
        // TODO add your handling code here:
        jButton7_F.setForeground(Color.white);
        jButton7_F.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_jButton7_FMouseEntered

    private void jButton7_FMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7_FMouseExited
        // TODO add your handling code here:
        jButton7_F.setForeground(Color.black);
        jButton7_F.setBackground(new Color(248,148,6));
    }//GEN-LAST:event_jButton7_FMouseExited

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
        jButton8.setForeground(Color.white);
        jButton8.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
        jButton8.setForeground(Color.black);
        jButton8.setBackground(new Color(248,148,6));
    }//GEN-LAST:event_jButton8MouseExited

    public void addToCart(int id)
    {
        String ans=JOptionPane.showInputDialog(null,"Quanitity");
        if(ans == null){
            return;
        }
        boolean flag=true;
        for(int i =0;i<ans.length() && flag;i++){
            if(ans.charAt(i)>='0' && ans.charAt(i)<='9'){
                flag=true;
            }
            else{
                flag=false;
            }
        }
        if(!flag){
            return;
        }
        else
        {
            int uq=Integer.parseInt(ans);
            if(uq==0){
                return;
            }
            PreparedStatement st;
            ResultSet rs;
            int q=0;
            String query="SELECT * FROM menu where itemID=?";
            try 
            {
                st=db_connection.getConnection().prepareStatement(query);
                st.setInt(1, id);
                rs=st.executeQuery();
                if(rs.next())
                {
                    q=rs.getInt("quantity");
                    if(q>1){
                        if(uq<q){
                            int itemid=rs.getInt("itemID");
                            String itemNm=rs.getString("name");
                            int itemPr=rs.getInt("price");
                        
                            String serQuery="SELECT itemID FROM orders WHERE itemID=?";
                            PreparedStatement sqps=db_connection.getConnection().prepareStatement(serQuery);
                            sqps.setInt(1,itemid);
                            ResultSet sers=sqps.executeQuery();
                            String ordItemQuery="";
                            if(sers.next()){
                                ordItemQuery="UPDATE `orders` SET `quantity`=? WHERE itemID=?";
                            }
                            else{
                                ordItemQuery="INSERT INTO `orders` (`itemID`, `name`, `price`, `quantity`) VALUES (?,?,?,?)";
                            }
                            PreparedStatement otps=db_connection.getConnection().prepareStatement(ordItemQuery);
                            if(sers.next())
                            {
                                otps.setInt(1, uq);
                                otps.setInt(2, itemid);
                            }
                            else
                            {
                                otps.setInt(1, itemid);
                                otps.setString(2, itemNm);
                                otps.setInt(3, itemPr);
                                otps.setInt(4, uq);
                            }
                            if(otps.executeUpdate()>0)
                            {
                                JOptionPane.showMessageDialog(null, "Added to cart");
                            }
                        }
                        else{
                            JOptionPane.showInputDialog(null, "Desired quantity isn't available", "Quantity");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Item not available currently");
                    }
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1_M;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3_C;
    private javax.swing.JButton jButton4_Q;
    private javax.swing.JButton jButton5_P;
    private javax.swing.JButton jButton6_S;
    private javax.swing.JButton jButton7_F;
    private javax.swing.JButton jButton8;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12_cart;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5_home;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField2_CNm;
    private javax.swing.JTextField jTextField2_FNm;
    private javax.swing.JTextField jTextField2_MNm;
    private javax.swing.JTextField jTextField2_MPr;
    private javax.swing.JTextField jTextField2_PNm;
    private javax.swing.JTextField jTextField2_QNm;
    private javax.swing.JTextField jTextField2_SNm;
    private javax.swing.JTextField jTextField3_CPr;
    private javax.swing.JTextField jTextField4_QPr;
    private javax.swing.JTextField jTextField5_PPr;
    private javax.swing.JTextField jTextField6_SPr;
    private javax.swing.JTextField jTextField7_FPr;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
