
import java.sql.PreparedStatement;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public String email;
    //homeScreen h=new homeScreen();
    public Register() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8_name4 = new javax.swing.JLabel();
        jTextField7_name4 = new javax.swing.JTextField();
        jLabel2_email4 = new javax.swing.JLabel();
        jTextField1_email4 = new javax.swing.JTextField();
        jLabel3_pass4 = new javax.swing.JLabel();
        jLabel6_conpass4 = new javax.swing.JLabel();
        jLabel4_Pno4 = new javax.swing.JLabel();
        jTextField4_Pno4 = new javax.swing.JTextField();
        jLabel5_add4 = new javax.swing.JLabel();
        jTextField5_add4 = new javax.swing.JTextField();
        jButton1_register4 = new javax.swing.JButton();
        jButton2_cancel4 = new javax.swing.JButton();
        jPasswordField1_pass4 = new javax.swing.JPasswordField();
        jPasswordField2_conpass4 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 51));

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));

        jPanel7.setBackground(new java.awt.Color(44, 62, 80));

        jLabel8_name4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel8_name4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8_name4.setText("Name");

        jTextField7_name4.setBackground(new java.awt.Color(108, 122, 137));
        jTextField7_name4.setForeground(new java.awt.Color(228, 241, 254));
        jTextField7_name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7_nameActionPerformed(evt);
            }
        });

        jLabel2_email4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel2_email4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2_email4.setText("E-Mail");

        jTextField1_email4.setBackground(new java.awt.Color(108, 122, 137));
        jTextField1_email4.setForeground(new java.awt.Color(228, 241, 254));
        jTextField1_email4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_emailActionPerformed(evt);
            }
        });

        jLabel3_pass4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel3_pass4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3_pass4.setText("Password");

        jLabel6_conpass4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel6_conpass4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6_conpass4.setText("Confirm Password");

        jLabel4_Pno4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel4_Pno4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4_Pno4.setText("Phone No.");

        jTextField4_Pno4.setBackground(new java.awt.Color(108, 122, 137));
        jTextField4_Pno4.setForeground(new java.awt.Color(228, 241, 254));
        jTextField4_Pno4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4_PnoKeyTyped(evt);
            }
        });

        jLabel5_add4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabel5_add4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5_add4.setText("Address");

        jTextField5_add4.setBackground(new java.awt.Color(108, 122, 137));
        jTextField5_add4.setForeground(new java.awt.Color(228, 241, 254));

        jButton1_register4.setBackground(new java.awt.Color(34, 167, 240));
        jButton1_register4.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jButton1_register4.setText("Register");
        jButton1_register4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1_registerMouseExited(evt);
            }
        });
        jButton1_register4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_registerActionPerformed(evt);
            }
        });

        jButton2_cancel4.setBackground(new java.awt.Color(34, 167, 240));
        jButton2_cancel4.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jButton2_cancel4.setText("Cancel");
        jButton2_cancel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2_cancelMouseExited(evt);
            }
        });
        jButton2_cancel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_cancelActionPerformed(evt);
            }
        });

        jPasswordField1_pass4.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordField1_pass4.setForeground(new java.awt.Color(228, 241, 254));

        jPasswordField2_conpass4.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordField2_conpass4.setForeground(new java.awt.Color(228, 241, 254));

        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Already have an account??  Sign In ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1_register4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jButton2_cancel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_email4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3_pass4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_conpass4)
                            .addComponent(jLabel4_Pno4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5_add4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_email4)
                            .addComponent(jTextField7_name4)
                            .addComponent(jPasswordField2_conpass4)
                            .addComponent(jTextField4_Pno4)
                            .addComponent(jTextField5_add4)
                            .addComponent(jPasswordField1_pass4))))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8_name4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2_email4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1_email4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1_pass4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3_pass4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2_conpass4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6_conpass4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4_Pno4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4_Pno4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5_add4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5_add4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_register4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_cancel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setText("Register");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.black));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_cancelActionPerformed
        // TODO add your handling code here:
        homeScreen h=new homeScreen();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
        h.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2_cancelActionPerformed

    private void jButton2_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_cancelMouseExited
        // TODO add your handling code here:
        jButton2_cancel4.setForeground(Color.black);
        jButton2_cancel4.setBackground(new Color(34,167,240));
    }//GEN-LAST:event_jButton2_cancelMouseExited

    private void jButton2_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_cancelMouseEntered
        // TODO add your handling code here:
        jButton2_cancel4.setForeground(Color.white);
        jButton2_cancel4.setBackground(new Color(242,38,19));
    }//GEN-LAST:event_jButton2_cancelMouseEntered

    private void jButton1_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_registerActionPerformed

        String name=jTextField7_name4.getText();
        email=jTextField1_email4.getText();
        String pno=jTextField4_Pno4.getText();
        String add=jTextField5_add4.getText();
        String pass=String.valueOf(jPasswordField1_pass4.getPassword());
        String conpass=String.valueOf(jPasswordField2_conpass4.getPassword());
        if(checkTextFields() && (!checkDuplicateEmail()))
        {
            PreparedStatement st;
            ResultSet rs;
            String query="INSERT INTO `customer`(`name`, `email`, `password`, `address`, `number`) VALUES (?,?,?,?,?)";
            try {
            st = db_connection.getConnection().prepareStatement(query);
            st.setString(1, name);
            st.setString(2, email);
            st.setString(3, pass);
            st.setString(4, add);
            st.setString(5, pno);
            
            if(st.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null, "Account Created successfully");
                Menu m=new Menu();
                m.setVisible(true);
                m.setLocationRelativeTo(null);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Error in Creating Account");
            }
        } 
       catch (SQLException ex) {}
        }
        
    }//GEN-LAST:event_jButton1_registerActionPerformed

    private void jButton1_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_registerMouseExited
        // TODO add your handling code here:
        jButton1_register4.setForeground(Color.black);
        jButton1_register4.setBackground(new Color(34,167,240));
    }//GEN-LAST:event_jButton1_registerMouseExited

    private void jButton1_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_registerMouseEntered
        // TODO add your handling code here:
        jButton1_register4.setForeground(Color.white);
        jButton1_register4.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_jButton1_registerMouseEntered

    private void jTextField4_PnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4_PnoKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4_PnoKeyTyped

    private void jTextField1_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_emailActionPerformed

    private void jTextField7_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7_nameActionPerformed

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setBorder(null);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        Border labelBorder=BorderFactory.createMatteBorder(0, 0, 2, 0,new Color(236,240,241));
        jLabel4.setBorder(labelBorder);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        SignIn s=new SignIn();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        s.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public boolean checkTextFields()
    {
        String name=jTextField7_name4.getText();
        email=jTextField1_email4.getText();
        String pno=jTextField4_Pno4.getText();
        String add=jTextField5_add4.getText();
        String pass=String.valueOf(jPasswordField1_pass4.getPassword());
        String conpass=String.valueOf(jPasswordField2_conpass4.getPassword());
        
        if(name.trim().equals("") || email.trim().equals("") || pno.trim().equals("") || add.trim().equals("") ||
                pass.trim().equals("") || conpass.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or more fields are EMPTY", "Empty Fields", 3);
            return false;
        }
        else if(!(pass.equals(conpass)))
        {
            JOptionPane.showMessageDialog(null, "Password doesn't match", "Unmatched Password", 3);
            return false;
        }
        else{return true;}
    }

   public boolean checkDuplicateEmail()
   {
       PreparedStatement st;
       ResultSet rs;
       email=jTextField1_email4.getText();
       String query="SELECT * FROM customer WHERE email=?";
       try {
            st = db_connection.getConnection().prepareStatement(query);
            st.setString(1, email);
            rs=st.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Email already Registered", "Duplicate Email", 3);
                return true;
            }
        } 
       catch (SQLException ex) {}
       return false;
   }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_register;
    private javax.swing.JButton jButton1_register1;
    private javax.swing.JButton jButton1_register2;
    private javax.swing.JButton jButton1_register3;
    private javax.swing.JButton jButton1_register4;
    private javax.swing.JButton jButton2_cancel;
    private javax.swing.JButton jButton2_cancel1;
    private javax.swing.JButton jButton2_cancel2;
    private javax.swing.JButton jButton2_cancel3;
    private javax.swing.JButton jButton2_cancel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2_email;
    private javax.swing.JLabel jLabel2_email1;
    private javax.swing.JLabel jLabel2_email2;
    private javax.swing.JLabel jLabel2_email3;
    private javax.swing.JLabel jLabel2_email4;
    private javax.swing.JLabel jLabel3_pass;
    private javax.swing.JLabel jLabel3_pass1;
    private javax.swing.JLabel jLabel3_pass2;
    private javax.swing.JLabel jLabel3_pass3;
    private javax.swing.JLabel jLabel3_pass4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_Pno;
    private javax.swing.JLabel jLabel4_Pno1;
    private javax.swing.JLabel jLabel4_Pno2;
    private javax.swing.JLabel jLabel4_Pno3;
    private javax.swing.JLabel jLabel4_Pno4;
    private javax.swing.JLabel jLabel5_add;
    private javax.swing.JLabel jLabel5_add1;
    private javax.swing.JLabel jLabel5_add2;
    private javax.swing.JLabel jLabel5_add3;
    private javax.swing.JLabel jLabel5_add4;
    private javax.swing.JLabel jLabel6_conpass;
    private javax.swing.JLabel jLabel6_conpass1;
    private javax.swing.JLabel jLabel6_conpass2;
    private javax.swing.JLabel jLabel6_conpass3;
    private javax.swing.JLabel jLabel6_conpass4;
    private javax.swing.JLabel jLabel8_name;
    private javax.swing.JLabel jLabel8_name1;
    private javax.swing.JLabel jLabel8_name2;
    private javax.swing.JLabel jLabel8_name3;
    private javax.swing.JLabel jLabel8_name4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1_pass;
    private javax.swing.JPasswordField jPasswordField1_pass1;
    private javax.swing.JPasswordField jPasswordField1_pass2;
    private javax.swing.JPasswordField jPasswordField1_pass3;
    private javax.swing.JPasswordField jPasswordField1_pass4;
    private javax.swing.JPasswordField jPasswordField2_conpass;
    private javax.swing.JPasswordField jPasswordField2_conpass1;
    private javax.swing.JPasswordField jPasswordField2_conpass2;
    private javax.swing.JPasswordField jPasswordField2_conpass3;
    private javax.swing.JPasswordField jPasswordField2_conpass4;
    private javax.swing.JTextField jTextField1_email;
    private javax.swing.JTextField jTextField1_email1;
    private javax.swing.JTextField jTextField1_email2;
    private javax.swing.JTextField jTextField1_email3;
    private javax.swing.JTextField jTextField1_email4;
    private javax.swing.JTextField jTextField4_Pno;
    private javax.swing.JTextField jTextField4_Pno1;
    private javax.swing.JTextField jTextField4_Pno2;
    private javax.swing.JTextField jTextField4_Pno3;
    private javax.swing.JTextField jTextField4_Pno4;
    private javax.swing.JTextField jTextField5_add;
    private javax.swing.JTextField jTextField5_add1;
    private javax.swing.JTextField jTextField5_add2;
    private javax.swing.JTextField jTextField5_add3;
    private javax.swing.JTextField jTextField5_add4;
    private javax.swing.JTextField jTextField7_name;
    private javax.swing.JTextField jTextField7_name1;
    private javax.swing.JTextField jTextField7_name2;
    private javax.swing.JTextField jTextField7_name3;
    private javax.swing.JTextField jTextField7_name4;
    // End of variables declaration//GEN-END:variables
}
